services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    volumes:
      - ./apps/backend:/app/apps/backend      # <-- Agora está mapeando para o mesmo do WORKDIR
      - ./apps/backend/static:/app/apps/backend/static
    env_file:
      - .env
    ports:
      - "8090:8000"
    networks:
      - app-network


  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    volumes:
      - ./apps/frontend:/app/apps/frontend   # Mapeia a pasta correta
      - /app/apps/frontend/node_modules       # Garante que os node_modules internos não sejam sobrescritos
    ports:
      - "3030:5173"   # Mapeia a porta 5173 do container para 3000 no host
    # Não precisa de command aqui, pois o CMD do Dockerfile já chama 'pnpm run dev'
    networks:
      - app-network
    env_file:
      - .env  

networks:
  app-network:
    driver: bridge
