services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    volumes:
      - ./apps/backend:/app/apps/backend      # <-- Agora está mapeando para o mesmo do WORKDIR
      - ./apps/backend/static:/app/apps/backend/static
    env_file:
      - .env.production
    ports:
      - "8090:8000"
    networks:
      - app-network


  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.prod
    ports:
      - "3030:80"
    networks:
      - app-network
    env_file:
      - .env.production

networks:
  app-network:
    driver: bridge