services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./apps/frontend
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules           # 👈 evita conflitos com node_modules do host
    ports:
      - "3000:5173"                 # 👈 redireciona porta do host 3000 → Vite 5173
    command: pnpm run dev           # 👈 roda Vite em modo dev (hot reload)

networks:
  app-network:
    driver: bridge
